server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.50.141:3306/proj_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: appuser
    password: RuanGongDemo!123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath*:com/szu/mapper/*.xml
  type-aliases-package: com.szu.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      blog:
        myblog:
          mapper: debug
          service: info
          controller: info

szu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: szuruangong
    # 设置jwt过期时间
    short-ttl: 600000
    long-ttl:  259200000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization
  wechat:
    appid: wx42f0f7a77c876fb3
    secret: b4e40efd78f6dbe713c8c00613c3d756
  alioss:
    endpoint: ${szu.alioss.endpoint}
    access-key-id: ${szu.alioss.access-key-id}
    access-key-secret: ${szu.alioss.access-key-secret}
    bucket-name: ${szu.alioss.bucket-name}