server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.50.141:3306/proj_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: appuser
    password: RuanGongDemo!123

mybatis:
  #mapper配置文件
  mapper-locations: classpath*:com/szu/mapper/*.xml
  type-aliases-package: com.szu.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      blog:
        myblog:
          mapper: debug
          service: info
          controller: info